### ISSUE TITLE
Ligature support

### ISSUE THREAD

**Issue by keathley** [lucasmazza/language-elixir#27]
There is limited support for ligatures like `|>` and `->`. This is because the current regex divides `|`, `>`, `-` and `>` as separate symbols and Atom can't combine the symbols into one ligature. I attempted to fix this myself but frankly my regex foo and knowledge of atom grammars is fairly weak. If you want to point me in the right direction I would be happy to work on this issue.

Also potentially related to #17.

Thanks for providing this package in the first place. Let me know if I can help.

**Comment by gusaiani** [comment]
+1, this is beautiful with Atom and FiraCode.

+1 to the thanks for this package as well, @lucasmazza ♕

**Comment by keathley** [comment]
Fixed in #30

**Comment by gusaiani** [comment]
This being implemented really made my day. Thanks!
